# -*- coding: utf-8 -*-
"""VehicleIdentification.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1e1ste68Dyc6dpUiO_rsDHcfHWuzo_-R0
"""

import csv

def identify_vehicle(color, height, weight, no_of_wheels):
    if no_of_wheels == 2 and weight <= 1200:
        return "Bike"
    elif no_of_wheels == 4 and weight >= 1800:
        return "Car"
    else:
        return "Unknown"

def identify_vehicle_type(no_of_wheels):
    if no_of_wheels == 2:
        return "Bike"
    elif no_of_wheels == 4:
        return "Car"
    else:
        return "Unknown"

def main():
    print("Welcome to the Vehicle Identification System\n")
    while True:
        print("Please enter vehicle details:")
        color = input("Color: ")
        height = int(input("Height (in cm): "))
        weight_kg = float(input("Weight (in kg): "))
        no_of_wheels = int(input("Number of wheels: "))

        # Identify the vehicle
        vehicle_type = identify_vehicle(color, height, weight_kg, no_of_wheels)

        # Show the output
        if vehicle_type in ["Bike", "Car"]:
            print(f"\nThe identified vehicle type is: {vehicle_type}")
        else:
            print("\nUnknown vehicle type")

        choice = input("\nDo you want to enter another vehicle? (yes/no): ")
        if choice.lower() != 'yes':
            break

    print("\nUpdating CSV file...")

    # Read data from the current CSV file
    data = []
    with open('random_data.csv', 'r') as infile:
        reader = csv.DictReader(infile)
        for row in reader:
            row['vehicle_type'] = identify_vehicle_type(int(row['no_of_wheels']))
            data.append(row)

    # Write data to a new CSV file
    with open('updated_vehicle_data.csv', 'w', newline='') as outfile:
        fieldnames = ['weight', 'height', 'color', 'no_of_wheels', 'vehicle_type']
        writer = csv.DictWriter(outfile, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(data)

    print("CSV file 'updated_vehicle_data.csv' has been created.")